#+ summary: LODlaundromat endpoint with SPARQL2Git
#+ endpoint: http://sparql.backend.lodlaundromat.org
#+ tags:
#+   - lod
#+ method: GET
#+ pagination: 50

select distinct ?Concept where {[] a ?Concept} LIMIT 20
